### ISSUE TITLE
Errors when running on CRT

### ISSUE THREAD

**Issue by that1crzywhtguy** [morfeus77/MiSTerTools#1]
I can get the script to load up on my CRT, but when I try to select a new INI, I get this on screen and it won't swap.
![rn_image_picker_lib_temp_176e71e8-a0aa-40b1-aecc-9fcdccc36c67](https://github.com/morfeus77/MiSTerTools/assets/44032586/000af21b-a459-4e7e-96e1-05a267a152f3) 
![rn_image_picker_lib_temp_13c7b742-135d-4ee7-9c0b-1aa6396f9179](https://github.com/morfeus77/MiSTerTools/assets/44032586/9d76bb5e-dc90-4be9-8f2f-9eaf4e5b359e)

**Comment by morfeus77** [comment]
The reason for this issue is screen resolution.  I haven't been able to test it at these low resolutions (I don't own a display capable of 240p) but I can deduce from the error the script is running out of screen space.  The error is preventing the popup window to confirm changes to display which explains why it isn't applying changes.  You could try changing the line and columns number in the script.  The 7 and 48 on the line where it throws the error are the number of lines and columns.

**Comment by that1crzywhtguy** [comment]
Thanks for the reply! Have a suggestion what I should change them to?

**Comment by morfeus77** [comment]
I'm only guessing but maybe the easiest fix is to let the confirmation window popup in the top left corner:
so change lines 211 and 212 from 


    box1 = curses.newwin(7, 48, start_y-4, start_x-28)
    box2 = curses.newwin(5, 45 ,start_y-3, start_x-26)

to 

    box1 = curses.newwin(8, 35, 0, 0)
    box2 = curses.newwin(7, 34, 1, 1)

This might result in the text not fitting into the box drawn but you should at least be able to continue.  If that still throws an error try lowering the values 35 and 34 to even lower numbers.  Let me know what worked for you so I can add this change for low resolution displays.

**Comment by that1crzywhtguy** [comment]
That did it for me! Works now on my PVMs. :)

My dreams of 8 INI files are finally true! haha

**Comment by morfeus77** [comment]
Good to hear. I will upload a newer version soon that will implement this (detect 240p and confirmation popup window in top left corner).
